theme: jekyll-theme-slate

# Site settings
title: David McArtor - Multidisciplinary Professional  # Your site title
description: >  # A short description of your site's purpose
  My personal portfolio showcasing professional credentials and data science projects.

# URL settings (uncomment and modify if necessary)
# url: "https://yourusername.github.io"  # The base hostname & protocol for your site
# baseurl: "/repository-name"  # The subpath of your site, e.g., /blog

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed  # Creates an Atom feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
#exclude:
#  - Gemfile
#  - Gemfile.lock

# Optional features
#show_downloads: true  # Show or hide the Download ZIP button
#google_analytics: [Your Google Analytics tracking ID]  # Enable Google Analytics tracking (optional)

# Social links (optional)
#twitter_username: yourusername  # Your Twitter handle
#github_username:  yourgithubusername  # Your GitHub username

# Build your navigation menu (optional)
navigation:  # Define navigation links
  - name: About
    link: /#about
  - name: Experience
    link: /#experience
  - name: Education
    link: /#education
  - name: Portfolio
    link: /#portfolio
  - name: Contact
    link: /#contact
